from setuptools import setup

setup (
        name="thonny-rpi-pico",
        version="0.2",
        description="PRIVATE! Support for RPi Pico (will be merged into Thonny later)",
        url="https://github.com/raspberrypi/thonny-pico/",
        author="Aivar Annamaa",
        author_email="aivar.annamaa@gmail.com",
        license="MIT",
        classifiers=[
          "Environment :: MacOS X",
          "Environment :: Win32 (MS Windows)",
          "Environment :: X11 Applications",
          "Intended Audience :: Developers",
          "Intended Audience :: Education",
          "Intended Audience :: End Users/Desktop",
          "License :: Freeware",
          "License :: OSI Approved :: MIT License",
          "Natural Language :: English",
          "Operating System :: MacOS",
          "Operating System :: Microsoft :: Windows",
          "Operating System :: POSIX",
          "Operating System :: POSIX :: Linux",
          "Programming Language :: Python",
          "Programming Language :: Python :: 3",
          "Programming Language :: Python :: 3 :: Only",
          "Programming Language :: Python :: 3.5",
          "Programming Language :: Python :: 3.6",
          "Programming Language :: Python :: 3.7",
          "Programming Language :: Python :: 3.8",
          "Programming Language :: Python :: 3.9",
          "Topic :: Education",
          "Topic :: Software Development",
          "Topic :: Software Development :: Embedded Systems",
        ],
        keywords="IDE education programming Thonny MicroPython",
        platforms=["Windows", "macOS", "Linux"],
        python_requires=">=3.5",
        install_requires=["thonny >= 3.3.0b6"],
        packages=["thonnycontrib.rpi_pico"],
        include_package_data=True,
        package_data={'thonnycontrib.rpi_pico': ['api_stubs/*']},
)